export PS1="\[\033[0;37m\]\u@\h\[\033[0;32m\] \w \$\[\033[00m\] "
export CLICOLOR=1

shopt -s histappend

alias ls='ls -a --color'
alias ll='ls -ahl --color'
alias rm='rm -i'

case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac
