set nocompatible
set history=50
set ruler               " show the cursor position all the time
set showcmd             " display incomplete commands

set expandtab       " convert tabs to spaces
set tabstop=4       " 4 spaces to a tab
set shiftwidth=4    " 4 spaces for indentation
syntax on
nmap <C-N><C-N> :set invnumber<CR>
set invnumber
set autoindent
autocmd BufRead,BufNewFile *.eyaml set filetype=yaml
